# Generated by Django 3.1.3 on 2021-02-25 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210223_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card', to='store.customer'),
        ),
        migrations.AlterField(
            model_name='filtercategory',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_category', to='store.itemcategory'),
        ),
        migrations.AlterField(
            model_name='filtername',
            name='filter_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_name', to='store.filtercategory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='store.itemcategory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='store.customer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item', to='store.customer'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_address', to='store.customer'),
        ),
    ]
