# Generated by Django 3.1.3 on 2021-02-25 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210224_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.customer'),
        ),
        migrations.AlterField(
            model_name='filtercategory',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.itemcategory'),
        ),
        migrations.AlterField(
            model_name='filtername',
            name='filter_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.filtercategory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.itemcategory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.shippingaddress'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.customer'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.customer'),
        ),
    ]
