# Generated by Django 3.1.3 on 2021-02-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210224_2345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilterName',
            new_name='FilterOption',
        ),
        migrations.RemoveField(
            model_name='item',
            name='filter_name',
        ),
        migrations.AddField(
            model_name='item',
            name='filter_option',
            field=models.ManyToManyField(blank=True, to='store.FilterOption'),
        ),
    ]
