# Generated by Django 3.1.3 on 2021-02-28 01:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210226_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='purchase_attempt_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 1, 57, 37, 145681, tzinfo=utc)),
        ),
    ]
