# Generated by Django 3.1.3 on 2021-02-28 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210227_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='purchase_attempt_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
