# Generated by Django 3.1.3 on 2021-03-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210301_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
