# Generated by Django 3.1.3 on 2021-02-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210222_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='reset_msg_time',
            new_name='send_msg_time',
        ),
    ]
