# Generated by Django 3.1.3 on 2021-02-23 04:25

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=50)),
                ('description', models.CharField(default='Description', max_length=100)),
                ('body', ckeditor.fields.RichTextField(default='Text')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(default='Author', max_length=50)),
                ('date_pub', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.category')),
            ],
        ),
    ]
